import {
    FileText,
    Newspaper,
    Image,
    Settings,
    Palette,
    Puzzle,
    Users,
    LayoutDashboard,
    Menu,
    Tags,
    LayoutGrid,
    LayoutTemplate,
    MessageSquare,
    BarChart3,
    Globe,
    ClipboardList,
    Mail,
    HardDrive,
    Sparkles,
    Truck,
    Receipt,
    Star,
    Warehouse,
    Package,
    ShoppingCart,
    Ticket,
    FolderTree,
} from 'lucide-react';
import { type CommandItem } from './types';

export const COMMANDS: CommandItem[] = [
    // Content
    {
        id: 'dashboard',
        label: 'Tableau de bord',
        icon: LayoutDashboard,
        href: '/admin',
        category: 'Contenu',
    },
    {
        id: 'pages',
        label: 'Pages',
        icon: FileText,
        href: '/admin/pages',
        category: 'Contenu',
        keywords: ['page', 'contenu'],
    },
    {
        id: 'pages-new',
        label: 'Nouvelle page',
        icon: FileText,
        href: '/admin/pages/create',
        category: 'Contenu',
        keywords: ['creer', 'nouveau'],
    },
    {
        id: 'posts',
        label: 'Articles',
        icon: Newspaper,
        href: '/admin/posts',
        category: 'Contenu',
        keywords: ['blog', 'article'],
    },
    {
        id: 'posts-new',
        label: 'Nouvel article',
        icon: Newspaper,
        href: '/admin/posts/create',
        category: 'Contenu',
        keywords: ['creer', 'nouveau', 'blog'],
    },
    {
        id: 'media',
        label: 'Medias',
        icon: Image,
        href: '/admin/media',
        category: 'Contenu',
        keywords: ['image', 'fichier', 'upload'],
    },
    {
        id: 'comments',
        label: 'Commentaires',
        icon: MessageSquare,
        href: '/admin/comments',
        category: 'Contenu',
    },

    // Structure
    {
        id: 'menus',
        label: 'Menus',
        icon: Menu,
        href: '/admin/menus',
        category: 'Structure',
        keywords: ['navigation'],
    },
    {
        id: 'taxonomies',
        label: 'Taxonomies',
        icon: Tags,
        href: '/admin/taxonomies',
        category: 'Structure',
        keywords: ['categorie', 'tag'],
    },
    {
        id: 'widgets',
        label: 'Widgets',
        icon: LayoutGrid,
        href: '/admin/widgets',
        category: 'Structure',
        keywords: ['sidebar'],
    },
    {
        id: 'global-sections',
        label: 'Sections globales',
        icon: LayoutTemplate,
        href: '/admin/global-sections',
        category: 'Structure',
        keywords: ['header', 'footer'],
    },

    // Appearance
    {
        id: 'themes',
        label: 'Themes',
        icon: Palette,
        href: '/admin/themes',
        category: 'Apparence',
    },
    {
        id: 'style-book',
        label: 'Style Book',
        description: 'Design Tokens',
        icon: Palette,
        href: '/admin/design-tokens',
        category: 'Apparence',
        keywords: ['token', 'couleur', 'style'],
    },
    {
        id: 'plugins',
        label: 'Plugins',
        icon: Puzzle,
        href: '/admin/plugins',
        category: 'Apparence',
        keywords: ['extension'],
    },
    {
        id: 'templates',
        label: 'Templates',
        icon: LayoutTemplate,
        href: '/admin/templates',
        category: 'Apparence',
    },

    // Boutique
    {
        id: 'shop-products',
        label: 'Produits',
        icon: Package,
        href: '/admin/shop/products',
        category: 'Boutique',
        keywords: ['product', 'produit'],
    },
    {
        id: 'shop-orders',
        label: 'Commandes',
        icon: ShoppingCart,
        href: '/admin/shop/orders',
        category: 'Boutique',
        keywords: ['order', 'commande'],
    },
    {
        id: 'shop-coupons',
        label: 'Coupons',
        icon: Ticket,
        href: '/admin/shop/coupons',
        category: 'Boutique',
        keywords: ['coupon', 'promo', 'reduction'],
    },
    {
        id: 'shop-categories',
        label: 'Categories boutique',
        icon: FolderTree,
        href: '/admin/shop/categories',
        category: 'Boutique',
        keywords: ['categorie'],
    },
    {
        id: 'shop-shipping',
        label: 'Livraison',
        icon: Truck,
        href: '/admin/shop/shipping',
        category: 'Boutique',
        keywords: ['shipping', 'expedition'],
    },
    {
        id: 'shop-tax',
        label: 'Taxes',
        icon: Receipt,
        href: '/admin/shop/tax',
        category: 'Boutique',
        keywords: ['tva', 'taxe'],
    },
    {
        id: 'shop-stock',
        label: 'Stock',
        icon: Warehouse,
        href: '/admin/shop/stock',
        category: 'Boutique',
        keywords: ['inventaire'],
    },
    {
        id: 'shop-reviews',
        label: 'Avis clients',
        icon: Star,
        href: '/admin/shop/reviews',
        category: 'Boutique',
        keywords: ['review', 'avis'],
    },
    {
        id: 'shop-reports',
        label: 'Rapports ventes',
        icon: BarChart3,
        href: '/admin/shop/reports',
        category: 'Boutique',
        keywords: ['stats', 'ventes', 'rapport'],
    },
    {
        id: 'shop-settings',
        label: 'Parametres boutique',
        icon: Settings,
        href: '/admin/shop/settings',
        category: 'Boutique',
        keywords: ['shop', 'config'],
    },

    // Outils
    {
        id: 'forms',
        label: 'Form Builder',
        icon: ClipboardList,
        href: '/admin/forms',
        category: 'Outils',
        keywords: ['form', 'formulaire', 'soumission', 'builder'],
    },
    {
        id: 'contact',
        label: 'Messages contact',
        icon: Mail,
        href: '/admin/plugins/contact-form/submissions',
        category: 'Outils',
        keywords: ['contact', 'message'],
    },
    {
        id: 'backups',
        label: 'Sauvegardes',
        icon: HardDrive,
        href: '/admin/backups',
        category: 'Outils',
        keywords: ['backup', 'restore', 'sauvegarde'],
    },
    {
        id: 'ai-settings',
        label: 'Assistant IA',
        icon: Sparkles,
        href: '/admin/ai/settings',
        category: 'Outils',
        keywords: ['ia', 'ai', 'openai', 'anthropic'],
    },

    // System
    {
        id: 'settings',
        label: 'Parametres',
        icon: Settings,
        href: '/admin/settings',
        category: 'Systeme',
        keywords: ['config'],
    },
    {
        id: 'users',
        label: 'Utilisateurs',
        icon: Users,
        href: '/admin/users',
        category: 'Systeme',
        keywords: ['user', 'role'],
    },
    {
        id: 'analytics',
        label: 'Analytiques',
        icon: BarChart3,
        href: '/admin/analytics',
        category: 'Systeme',
        keywords: ['stats', 'trafic'],
    },
    {
        id: 'sites',
        label: 'Sites',
        icon: Globe,
        href: '/admin/sites',
        category: 'Systeme',
        keywords: ['multisite'],
    },
];
